title: CODEX
description: Software Engineering Illustrated Guide
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
site:
  url: https://01011111.github.io/codex/
  baseurl: /codex
